# @package dataset
defaults:
  - nlp/default
_target_: lightning_transformers.task.nlp.token_classification.TokenClassificationDataModule
cfg:
  task_name: spacing
  dataset_name: ekonspacing
  preprocessing_num_workers: 50
  label_all_tokens: False
  pad_to_max_length: False